apiVersion: apps/v1
kind: Deployment
metadata:
  name: springcloud-gateway
  namespace: mosaic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springcloud-gateway
  template:
    metadata:
      labels:
        app: springcloud-gateway
    spec:
      nodeSelector:
        disktype: control # 컨트롤 노드에 배치
      containers:
        - name: gateway
          image: ${DOCKERHUB_USERNAME}/mosaic-springcloud-gateway:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s

--- # Gateway Service 정의
apiVersion: v1
kind: Service
metadata:
  name: springcloud-gateway
  namespace: mosaic
spec:
  selector:
    app: springcloud-gateway
  ports:
    - port: 8080
      targetPort: 8080
