apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mosaic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        disktype: control
      containers:
        - name: frontend
          image: ${DOCKERHUB_USERNAME}/mosaic-${SERVICE_NAME}:${IMAGE_TAG}
          ports:
            - containerPort: 80
            - containerPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mosaic
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080 # 노드포트로 열 포트 번호
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443 # 노드포트로 열 포트 번호
