apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: mosaic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      nodeSelector:
        disktype: worker
      containers:
        - name: zookeeper
          image: ${DOCKERHUB_USERNAME}/mosaic-zookeeper:${IMAGE_TAG}
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          ports:
            - containerPort: 2181
          envFrom:
            - configMapRef:
                name: common-env
--- # Zookeeper Service 정의
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: mosaic
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
