services:
  member-api:
    build:
      context: ./back/member-service
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-default}/mosaic-member-api:${IMAGE_TAG:-local}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://member-db:3306/mosaic_member
      - SPRING_DATASOURCE_USERNAME=member
      - SPRING_DATASOURCE_PASSWORD=608
    env_file:
      - ./back/member-service/.env
    ports:
      - "18081:8080"

  account-api:
    build:
      context: ./back/account-service
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-default}/mosaic-account-api:${IMAGE_TAG:-local}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://account-db:3306/mosaic_account
      - SPRING_DATASOURCE_USERNAME=account
      - SPRING_DATASOURCE_PASSWORD=608
    ports:
      - "18082:8080"

  contract-api:
    build:
      context: ./back/contract-service
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-default}/mosaic-contract-api:${IMAGE_TAG:-local}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://contract-db:3306/mosaic_contract
      - SPRING_DATASOURCE_USERNAME=contract
      - SPRING_DATASOURCE_PASSWORD=608
    ports:
      - "18083:8080"
  credit-api:
    build:
      context: ./back/credit-service
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-default}/mosaic-credit-api:${IMAGE_TAG:-local}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://credit-db:3306/mosaic_credit
      - SPRING_DATASOURCE_USERNAME=credit
      - SPRING_DATASOURCE_PASSWORD=608
    ports:
      - "18084:8080"
  mydata-api:
    build:
      context: ./back/mydata-service
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-default}/mosaic-mydata-api:${IMAGE_TAG:-local}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mydata-db:3306/mosaic_mydata
      - SPRING_DATASOURCE_USERNAME=mydata
      - SPRING_DATASOURCE_PASSWORD=608
    ports:
      - "18085:8080"

  frontend-react:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-default}/mosaic-frontend:${IMAGE_TAG:-local}
    profiles:
      - build-only
    ports:
      - "80:80"
    depends_on:
      - springcloud-gateway

  springcloud-gateway:
    build:
      context: ./infra/springcloud-gateway
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-default}/mosaic-springcloud-gateway:${IMAGE_TAG:-local}
    ports:
      - "8080:8080"

  nginx:
    build:
      context: ./infra/nginx
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-default}/mosaic-nginx:${IMAGE_TAG:-local}
    ports:
      - "80:80"
    depends_on:
      - springcloud-gateway
  redis:
    build:
      context: ./infra/redis
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-default}/mosaic-redis:${IMAGE_TAG:-local}
    ports:
      - "6379:6379"

  zookeeper:
    build:
      context: ./infra/zookeeper
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-default}/mosaic-zookeeper:${IMAGE_TAG:-local}
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    build:
      context: ./infra/kafka
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-default}/mosaic-kafka:${IMAGE_TAG:-local}
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  member-db:
    build:
      context: ./infra/rdbms/member
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-default}/mosaic-member-db:${IMAGE_TAG:-local}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mosaic_member
      MYSQL_USER: member
      MYSQL_PASSWORD: 608
    ports:
      - "3307:3306"

  account-db:
    build:
      context: ./infra/rdbms/account
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-default}/mosaic-account-db:${IMAGE_TAG:-local}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mosaic_account
      MYSQL_USER: account
      MYSQL_PASSWORD: 608
    ports:
      - "3308:3306"

  contract-db:
    build:
      context: ./infra/rdbms/contract
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-default}/mosaic-contract-db:${IMAGE_TAG:-local}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mosaic_contract
      MYSQL_USER: contract
      MYSQL_PASSWORD: 608
    ports:
      - "3309:3306"

  mydata-db:
    build:
      context: ./infra/rdbms/mydata
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-default}/mosaic-mydata-db:${IMAGE_TAG:-local}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mosaic_mydata
      MYSQL_USER: mydata
      MYSQL_PASSWORD: 608
    ports:
      - "3310:3306"
  credit-db:
    build:
      context: ./infra/rdbms/credit
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-default}/mosaic-credit-db:${IMAGE_TAG:-local}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mosaic_credit
      MYSQL_USER: credit
      MYSQL_PASSWORD: 608
    ports:
      - "3311:3306"
