build_redis:
  variables:
    SERVICE_NAME: redis
    BUILD_CONTEXT: ./infra/redis
    K8S_PATH: ./infra/k8s/infras/redis.yml
  extends: .backend-default-build
  rules: 
    - changes: 
      - infra/redis/**/*

push_redis:
  variables:
    SERVICE_NAME: redis
    BUILD_CONTEXT: ./infra/redis
    K8S_PATH: ./infra/k8s/infras/redis.yml
  extends: .backend-default-push
  needs: [build_redis]
  rules: 
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"'     # 수동 실행도 허용하려면
      when: manual
    - when: never
    - changes: 
      - infra/redis/**/*

deploy_redis:
  variables:
    SERVICE_NAME: redis
    BUILD_CONTEXT: ./infra/redis
    K8S_PATH: ./infra/k8s/infras/redis.yml
  extends: .backend-default-deploy
  needs: [push_redis]
  rules: 
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "web"'     # 수동 실행도 허용하려면
      when: manual
    - when: never
    - changes: 
      - infra/redis/**/*
#test_include_trigger:
# tags:
#  - $GITLAB_USER_EMAIL
#script:
#  - echo "CI 정상 작동 여부 확인"
