--- # mydata DB Pod 정의 시작 (개발/테스트용)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mydata-db
  namespace: mosaic
spec:
  selector:
    matchLabels:
      app: mydata-db
  serviceName: mydata-db
  replicas: 1
  template:
    metadata:
      labels:
        app: mydata-db 
    spec:
      nodeSelector:
        disktype: worker
    spec:
      containers:
        - name: mysql
          image: ${DOCKERHUB_USERNAME}/mosaic-mydata-db:${IMAGE_TAG}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: mosaic_mydata
            - name: MYSQL_USER
              value: mydata
            - name: MYSQL_PASSWORD
              value: "608"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 30Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mydata-db
  namespace: mosaic
spec:
  clusterIP: None  # Headless Service (StatefulSet에서 권장)
  selector:
    app: mydata-db
  ports:
    - port: 3306
      targetPort: 3306