server:
    port: 8080
##
spring:
    application:
        name: credit-service
    datasource:
        url: ${CREDIT_DATASOURCE_URL}
        username: ${CREDIT_DATASOURCE_USERNAME}
        password: ${CREDIT_DATASOURCE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}

    kafka:
        bootstrap-servers: kafka:9092
